apiVersion: v1
kind: Service
metadata:
  name: configserver-service
spec:
  selector:
    app: configserver
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: dkg1437/config-server:latest
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_ZIPKIN_BASEURL
              valueFrom:
                configMapKeyRef:
                 name: dkg-configmap
                 key: SPRING_ZIPKIN_BASEURL
            - name: SPRING_PROFILE_ACTIVE
              valueFrom:
                configMapKeyRef:
                 name: dkg-configmap
                 key: SPRING_PROFILE_ACTIVE
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                 name: dkg-configmap
                 key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE  
