apiVersion: v1
kind: Service
metadata:
  name: department-service
spec:
  selector:
    app: department
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: department-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department
  template:
    metadata:
      labels:
        app: department
    spec:
      containers:
        - name: department-api
          image: dkg1437/department-server:latest
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_ZIPKIN_BASEURL
              valueFrom:
                configMapKeyRef:
                 name: dkg-configmap
                 key: SPRING_ZIPKIN_BASEURL
            - name: SPRING_PROFILE_ACTIVE
              valueFrom:
                configMapKeyRef:
                 name: dkg-configmap
                 key: SPRING_PROFILE_ACTIVE  
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                 name: dkg-configmap
                 key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE 
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                 name: dkg-configmap
                 key: SPRING_CONFIG_IMPORT                 
