apiVersion: v1
kind: Service
metadata:
  name: employee-service
spec:
  selector:
    app: employee
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
        - name: employee-api
          image: dkg1437/employee-server:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_ZIPKIN_BASEURL
              valueFrom:
                configMapKeyRef:
                 name: dkg-configmap
                 key: SPRING_ZIPKIN_BASEURL
            - name: SPRING_PROFILE_ACTIVE
              valueFrom:
                configMapKeyRef:
                 name: dkg-configmap
                 key: SPRING_PROFILE_ACTIVE  
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                 name: dkg-configmap
                 key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE 
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                 name: dkg-configmap
                 key: SPRING_CONFIG_IMPORT                 
